### ISSUE TITLE
[SERVER] #15 Make ReplyTable

### ISSUE THREAD

**Issue by riverpark94** [riverpark94/Notice_Board#15]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 댓글 내용 수정

### TODO
3. [x] Replys 테이블을 만듦
3. [x] Users 테이블과 FK 설정을 함.
3. [x] Boards 테이블과 FK 설정을 함.
3. [x] Replys 테이블(자기자신과)과 FK 설정을 함.

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2h`
- Group : `server`
- Sprint: `Sprint__2__`
- Urgency: `High`, `Middle`, `Low`
