### ISSUE TITLE
[SERVER] #2 join 

### ISSUE THREAD

**Issue by riverpark94** [riverpark94/Notice_Board#2]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: Sign Up구현

### TODO
1. [x] Users DB 만들기
2. [x] 라우터 분리 및 컨트롤러 폴더와 파일 만들기
2. [x] 이메일, 닉네임, 비밀번호 칼럼이 비어있는지 확인
3. [x] 닉네임 10자 초과인지 아닌지 확인
4. [x] 비밀번호에 영문과 숫자가 포함되지 않았는지 확인
5. [x] 이메일 양식 확인
5. [x] 이메일 중복 확인 후 USER DB에 데이터 저장
6. [x] 비밀번호를 단방향 암호화 하여 테이블에 저장

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `server`
- Sprint: `Sprint__1__`
- Urgency: `High`, `Middle`, `Low`
