### ISSUE TITLE
[SERVER] #3 Login 

### ISSUE THREAD

**Issue by riverpark94** [riverpark94/Notice_Board#3]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [x] 존재하지 않는 이메일일 경우 에러처리
    1.1 입력받은 이메일을 UsersDB 조회해서 정보 꺼내오기
2. [x]  비밀번호가 틀렸을 경우 에러처리
    2.1 기존 DB에서 salt 값꺼내기
    2.2 salt 값과 고객에게 입력받은 비밀번호를 조합해서 단방향 암호화된 비밀번호 만들기.
    2.3 2.2와 1.1의 비밀번호가 일치하는지 확인.
2. [x] 이메일과 비밀번호를 일치하면 해당 유저의 JWT 토큰을 발행한다.
3. [x] Response 값의 user 객체에는 비밀번호 필드를 포함시키지 않는다.

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1.5h`
- Group : `server`
- Sprint: `Sprint__1__`
- Urgency: `High`, `Middle`, `Low`
