### ISSUE TITLE
[SERVER] #7 Edit User Info

### ISSUE THREAD

**Issue by riverpark94** [riverpark94/Notice_Board#7]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 회원정보 수정

### TODO
1. [x] 회원정보 수정 전 비밀번호 확인을 하도록하기.
2. [x] 닉네임과 이메일 수정이 가능하게 만들기.
2. [x] 로그인이 안되어있으면 해당 기능을 사용할 수 없도록 설정

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2h`
- Group : `server`
- Sprint: `Sprint__2__`
- Urgency: `High`, `Middle`, `Low`
