### ISSUE TITLE
[SERVER] #9 Withdrawal

### ISSUE THREAD

**Issue by riverpark94** [riverpark94/Notice_Board#9]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 회원탈퇴 기능을 만든다.

### TODO
1. [x] User 테이블에서 로그인 하고 있는 사용자의 정보를 삭제한다.
2. [x] 이후 이 사용자가 작성한 게시글도 삭제됐는지를 확인한다.
3. [x] 이 기능을 수행한 후 `/`로 리 다이렉트를 하게 한다.

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2h`
- Group : `server`
- Sprint: `Sprint__1__`
- Urgency: `Middle`
